before_script:
- npm install
- npm install concurrently fs-extra live-server markdown-it nodemon babel-polyfill
script:
- npm run build-list
after_success:
- git update-index --add --chmod=+x push.sh
- chmod +x push.sh
- "./push.sh"
env:
  global:
    secure: B6SKqmvT0VgwAmrLbo5Ql5oP1Z33dHt7vfdRBb83iJhkF4XjfQn+55saEdB/z1v/gnlHNVhS1OSDFWSqyJ+bU36e+phS93ym98yKFexdNsIXFFKltyUp/ICgagj/sOw5ey+RELcpzHUrxi0zdQ1i1gMszP12FCATLlsPfiPPJpHtlpj07dFAeeH+4q8b2gw/KFAA62UVeW5FrE3ZzCVVCPY0nP7FpmyP6vUuNWhCU6/8p+um25v4xJNQ4jsT+DebjoikeQjsN04Oh2PHWC/RVOw1GUyfAF7SkcTfILzLjBZd2HDBK/YEMO/uCurCujE8qFzNEgU+koudXXKpY682DBBP78xlvFAW0+GiPBNoPz48/RvhE6xwmQkOyjf65W7gWYhPhxnmmRBwfhHBuwrn8SwIhWWLD78sb0Z/8ivw06DqMyjMnvvZ8MNvV+t2PMzrBN5awcBEty5C9g7HuIl3X8r8xbRdGGO8B5B3vF+oMkilr0RSgjYmr7r/DJcldhA1uTaYxdyQCL3E1SFjjJbSf0m6EvzHfcn893wdqlT1qWtcQyLAbRjm2J7hu2NABrhxk5LLqmLO/QkBNyA7eGlAaj+669jNcmY6LZq32pydL2/Jp8TEjeolg9gyZXKQk9ycoV/6YVM9wlCTCYfb2NIH66jwJfGH6a5I4Pz1Lcwm+qI=
